image: node:latest

cache:
  paths:
    - .cache/
    - .node_modules/
    - public/

stages:
  - pages

pages:
  stage: pages
  script:
    - npm ci
    - ./node_modules/gatsby/dist/bin/gatsby build
  artifacts:
    paths:
      - public
  only:
    - master
