image: node:latest

cache:
  paths:
    - .cache/
    - .node_modules/

stages:
  - build
  - pages

install:
  stage: build
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules

pages:
  stage: pages
  script:
    - ./node_modules/gatsby/bin/gatsby build
  artifacts:
    paths:
      - public
